language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# install required system libraries
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update --fix-missing -qq
  - sudo apt-get build-dep python-scipy -qq
# command to install dependencies from source
# note, separating requirements so that travis
# will get output in less than 5 min and won't
# terminate, using q to keep build info to a
# minumum for dependencies
install:
  - pip install -q numpy
  - pip install -q scipy
  - pip install -q slycot
  - pip install -q matplotlib

# command to run tests
script: python runtests.py
